#ifndef __GAME_H__
#define __GAME_H__

#include "Skills.h"
#include "Pokemon.h"
#include "Type.h"
#include "Item.h"
#include "Character.h"
#include "Rival.h"
#include "Pokemart.h"
#include "Battle.h"

class Game:
	public Pokemon,
	public Inventory
{
private:
	Character myChar;
	Rival myRival;

public:
	void beginGame();
	void createChar(std::string name);
	void createRival(std::string name);
	enum
	{
		BULBASAUR, IVYSAUR, VENUSAUR, CHARMANDER, CHARMELEON, CHARIZARD, SQUIRTLE, WARTORTLE, BLASTOISE, CATERPIE, METAPOD, BUTTERFREE, WEEDLE, KAKUNA, BEEDRILL, PIDGEY, PIDGEOTTO,
		PIDGEOT, RATTATA, RATICATE, SPEAROW, FEAROW, EKANS, ARBOK, PIKACHU, RAICHU, SANDSHREW, SANDSLASH, NIDORANF, NIDORINA, NIDOQUEEN, NIDORANM, NIDORINO, NIDOKING, CLEFAIRY, CLEFABLE,
		VULPIX, NINETALES, JIGGLYPUFF, WIGGLYTUFF, ZUBAT, GOLBAT, ODDISH, GLOOM, VILEPLUME, PARAS, PARASECT, VENONAT, VENOMOTH, DIGLETT, DUGTRIO, MEOWTH, PERSIAN, PSYDUCK, GOLDUCK, MANKEY,
		PRIMEAPE, GROWLITHE, ARCANINE, POLIWAG, POLIWHIRL, POLIWRATH, ABRA, KADABRA, ALAKAZAM, MACHOP, MACHOKE, MACHAMP, BELLSPROUT, WEEPINBELL, VICTREEBEL, TENTACOOL, TENTACRUEL, GEODUDE,
		GRAVELER, GOLEM, PONYTA, RAPIDASH, SLOWPOKE, SLOWBRO, MAGNEMITE, MAGNETON, FARFETCHD, DODUO, DODRIO, SEEL, DEWGONG, GRIMER, MUK, SHELLDER, CLOYSTER, GASTLY, HAUNTER, GENGAR, ONIX, 
		DROWZEE,HYPNO, KRABBY, KINGLER, VOLTORB, ELECTRODE, EXEGGCUTE, EXEGGUTOR, CUBONE, MAROWAK, HITMONLEE, HITMONCHAN, LICKITUNG, KOFFING, WEEZING, RHYHORN, RHYDON, CHANSEY, TANGELA, 
		KANGASKHAN, HORSEA, SEADRA, GOLDEEN, SEAKING, STARYU, STARMIE, MRMIME, SCYTHER, JYNX, ELECTABUZZ, MAGMAR, PINSIR, TAUROS, MAGIKARP, GYARADOS, LAPRAS, DITTO, EEVEE, VAPOREON, JOLTEON,
		FLAREON, PORYGON, OMANYTE, OMASTAR, KABUTO, KABUTOPS, AERODACTYL, SNORLAX, ARTICUNO, ZAPDOS, MOLTRES, DRATINI, DRAGONAIR, DRAGONITE, MEWTWO, MEW
	};
	enum
	{
		CONSTRICT, GUST, PECK, POISONSTING, POUND, SCRATCH, TACKLE, WINGATTACK, ACID, BUBBLE, CUT, DOUBLEKICK, LICK, QUICKATTACK, THUNDERSHOCK, VICEGRIP, BITE, CONFUSION, EMBER, HORNATTACK,
		KARATECHOP, RAZORLEAF, WATERGUN, ABSORB, AURORABEAM, BARRAGE, BIND, BONECLUB, BUBBLEBEAM, DRILLPECK, FURYATTACK, HIJUMPKICK, JUMPKICK, LOWKICK, MEGAPUNCH, PAYDAY, PETALDANCE,
		PINMISSILE, PSYBEAM, RAGE, SLAM, SLASH, SLUDGE, SMOG, STOMP, SUBMISSION, SWIFT, TAKEDOWN, THRASH, TWINEEDLE, WRAP, BODYSLAM, COMETPUNCH, DOUBLEEDGE, DREAMEATER, FIREPUNCH, FIRESPIN, 
		FLAMETHROWER, FLY, FURYSWIPES, HEADBUTT, HYPERFANG, ICEPUNCH, LEECHLIFE, ROCKTHROW, ROLLINGKICK, SKULLBASH, SPIKECANNON, STRENGTH, SURF, THUNDERBOLT, THUNDERPUNCH, WATERFALL, 
		BONEMERANG, CLAMP, CRABHAMMER, DIG, DIZZYPUNCH, DOUBLESLAP, EARTHQUAKE, EGGBOMB, ICEBEAM, MEGADRAIN, PSYCHIC, RAZORWIND, ROCKSLIDE, SOLARBEAM, THUNDER, TRIATTACK, VINEWHIP, BLIZZARD,
		EXPLOSION, FIREBLAST, HYDROPUMP, HYPERBEAM, MEGAKICK, SELFDESTRUCT, SKYATTACK, STRUGGLE
	};
	enum
	{
		ELIXIR,ETHER,FRESHWATER,FULLRESTORE,GREATBALL,HYPERPOTION,LEMONADE,MASTERBALL,MAXELIXIR,MAXETHER,MAXPOTION,MAXREVIVE,NUGGET,POKEBALL,POTION,RARECANDY,REVIVE,SODAPOP,SUPERPOTION,ULTRABALL
	};
};

#endif // !__GAME_H__